import React from 'react';
import { eventApi } from '../../../../api/api';
import Image from 'next/image';

export const metadata = {
	title: 'About us',
	description: 'Generated by create next app',
};
export default async function page() {
	const response = await eventApi();

	return (
		<>
			<div className='h-screen'>
				<h1 className=' text-4xl text-center pt-10'>ჩვენს შესახებ</h1>
				{response.map(res => (
					<>
						<Image width={350} height={197} src={res.image} alt={'image'} />
						<p key={res.id}>{res.category_name_ka}</p>
					</>
				))}
			</div>
		</>
	);
}
